POST http://localhost:3003/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm1vbmRheSIsImlkIjoxLCJpYXQiOjE2NzM5ODgxMzF9.csuprOI_6BGCf7eDzDLFRiRCSz0MH7wfFbwbY2XHdpI

{
  "content": "note created by logged in user",
  "important": false
}